 # pyMBE Tutorial: the Python-based Molecule Builder for ESPResSo.

The objective of pyMBE is to facilitate the set-up of complex molecules into the Molecular Dynamics software [espressomd.org](ESPResSo). pyMBE is specially well-suitedto facilitate setting up constant pH and grand-reaction ensemble simulations in ESPResSo.

## Table of contents:
* [Introduction](#introduction)
* [How to create particles](#particles)
* [How to create simple polymers](#simple_polymers)
* [How to create complex polymers](#complex_polymers)
* [How to create di-block copolymers](#diblock_copolymers)
* [Practice by creating branched polyampholytes](#branched_polyampholytes)
* [How to create peptides](#peptides)

## Introduction <a class="anchor" id="introduction"></a>

Let us get started by importing pyMBE library and other important libraries for this tutorial, such as ESPResSo.

In [1]:
# Import pyMBE and  ESPResSo
import pyMBE
import espressomd
from espressomd import interactions

Creating an instance of pyMBE we can make our code shorter and more readable.

In [2]:
pmb = pyMBE.pymbe_library(seed=42)

When pyMBE is inicialized, a default system of reduced units is defined. 

* Unit_length = 0.355 nm.
* Unit_charge = 1 elementary charge.
* Temperature = 298.15 K.

The active set of reduced units can be consulted using:

In [3]:
reduced_unit_set = pmb.get_reduced_units()
print(reduced_unit_set)

Current set of reduced units:
0.355 nanometer = 1 reduced_length
4.1164e-21 joule = 1 reduced_energy
1.6022e-19 coulomb = 1 reduced_charge
Temperature: 298.15 kelvin

This default definition of reduced units can be changed at the convience of the user using the following command:

In [4]:
pmb.set_reduced_units(unit_length = 0.5*pmb.units.nm,  
                      unit_charge = 5*pmb.units.e)
                      #, temperature=300*pmb.units.K)

WARNING:pint.util:Redefining 'reduced_energy' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
WARNING:pint.util:Redefining 'reduced_length' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
WARNING:pint.util:Redefining 'reduced_charge' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)

NOTE: All input variables will be given to ESPResSo using these reduced units, since it is a convenient choice for the simulation setup. Internally, pyMBE uses Pint library to deal with unit transformations, which in turn should be  used by the user to define its own variables.

Let us now create an instance of the ESPResSo system where we will place our molecules (a square simulation box with length = `box_l`).

In [5]:
Box_L = 7.5*pmb.units.nm

espresso_system = espressomd.System(box_l = [Box_L.to('reduced_length').magnitude]*3)

print('The side of the simulation box is ', Box_L, '=' ,Box_L.to('reduced_length'))

The side of the simulation box is  7.5 nanometer = 15.0 reduced_length

## How to create particles <a class="anchor" id="particles"></a>

Particles are the smaller objects in the simulation box, which can represent small ions or other small chemical species. In turn, particles can also be used as building blocks for larger molecules or polymers, where they can represent one monomeric unit or part of it. Particle objects are used in pyMBE as input for several of its funcionalities, including to create larger molecules and peptides. The basic properties of a particle are:

In [6]:
cation_name = 'Na'
pmb.define_particle(name = cation_name, 
                    z = 0, 
                    sigma = 0.35*pmb.units.nm, 
                    epsilon = 1*pmb.units('reduced_energy'))

pyMBE stores the properties of each different particle type or particle "template" on its internal database. To check all particle templates defined in the pyMBE database, one can query the pyMBE database manager:

In [7]:
pmb.get_templates_df(pmb_type = 'particle')

,pmb_type,name,sigma,epsilon,cutoff,offset,initial_state
0,particle,Na,0.35 nanometer,25.69257912108585 millielectron_volt,0.5612310241546865 nanometer,0.0 nanometer,Na

One can use pyMBE to create any number of the defined particles into the ESPResSo system.

In [8]:
N_cations = 20
pmb.create_particle(name = cation_name,
                    number_of_particles = N_cations,
                    espresso_system = espresso_system)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

pyMBE keeps track of each instance of a particle template created into the ESPResSo system. To check all particle instances created, one can query the pyMBE database manager:

In [9]:
pmb.get_instances_df(pmb_type = 'particle')

,pmb_type,name,particle_id,initial_state,residue_id,molecule_id,assembly_id
0,particle,Na,0,Na,<NA>,<NA>,<NA>
1,particle,Na,1,Na,<NA>,<NA>,<NA>
2,particle,Na,2,Na,<NA>,<NA>,<NA>
3,particle,Na,3,Na,<NA>,<NA>,<NA>
4,particle,Na,4,Na,<NA>,<NA>,<NA>
5,particle,Na,5,Na,<NA>,<NA>,<NA>
6,particle,Na,6,Na,<NA>,<NA>,<NA>
7,particle,Na,7,Na,<NA>,<NA>,<NA>
8,particle,Na,8,Na,<NA>,<NA>,<NA>
9,particle,Na,9,Na,<NA>,<NA>,<NA>
10,particle,Na,10,Na,<NA>,<NA>,<NA>
11,particle,Na,11,Na,<NA>,<NA>,<NA>
12,particle,Na,12,Na,<NA>,<NA>,<NA>
13,particle,Na,13,Na,<NA>,<NA>,<NA>
14,particle,Na,14,Na,<NA>,<NA>,<NA>
15,particle,Na,15,Na,<NA>,<NA>,<NA>
16,particle,Na,16,Na,<NA>,<NA>,<NA>
17,particle,Na,17,Na,<NA>,<NA>,<NA>
18,particle,Na,18,Na,<NA>,<NA>,<NA>
19,particle,Na,19,Na,<NA>,<NA>,<NA>

Let us see the particles that we have created by visualizing our ESPResSo system.

In [10]:
# Only necessary to produce the pictures used in this tutorial
from PIL import Image
def create_snapshot_of_espresso_system(espresso_system, filename):
    """
    Uses espresso visualizer for creating a snapshot of the current state of the espresso_system

    Args:
        espresso_system(`espressomd.system.System`): Instance of a system object from the espressomd library.
        filename(`str`): Name of the ouput file for the snapshot
    """ 
    from espressomd import visualization
    visualizer = visualization.openGLLive(
            espresso_system, bond_type_radius=[0.3], particle_coloring='type', draw_axis=False, background_color=[1, 1, 1],
    particle_type_colors=[[1.02,0.51,0], # Brown
                        [1,1,1],  # Grey
                        [2.55,0,0], # Red
                        [0,0,2.05],  # Blue
                        [0,0,2.05],  # Blue
                        [2.55,0,0], # Red
                        [2.05,1.02,0]]) # Orange
    visualizer.screenshot(filename)
    return
picture_name = 'cation_system.png'
create_snapshot_of_espresso_system(espresso_system = espresso_system, 
                               filename = picture_name)
img = Image.open(picture_name)
img.show()

To delete any instance of a particle created with pyMBE from the ESPResSo system we can use the following command:

In [11]:
# First search for the ids of the particles to delete
particle_id_map = pmb.get_particle_id_map(object_name=cation_name)
# This will delete all particles that we created before
for pid in particle_id_map["all"]:
    pmb.delete_instances_in_system(instance_id=pid, 
                                   pmb_type="particle",
                                  espresso_system = espresso_system)

If we query again the pyMBE database for particle instances in the ESPResSo system, we can observe that all particles have been deleted

In [12]:
pmb.get_instances_df(pmb_type = 'particle')

Empty DataFrame
Columns: []
Index: []


## How to create simple polymers <a class="anchor" id="simple_polymers"></a>

pyMBE can be used to easily construct coarse-grained models of simple polymers. Let us consider a coarse grained model for polydehydroalanaline (PDha) (figure below) in which its monomeric unit can be represented by three beads, as depicted in the schematics below: a backbone bead (grey), a bead for the carboxylic acid group (red) and a bead for the amino group (blue).

<img src="../figs/PDha.png" width=150 height=150 />

To set up such polymer with pyMBE first one has to define templates for the different particles in the monomer.

In [13]:
PDha_backbone_bead = 'BB-PDha'
PDha_carboxyl_bead = 'COOH-PDha'
PDha_amine_bead = 'NH3-PDha'

pmb.define_particle(name = PDha_backbone_bead, 
                    z = 0, 
                    sigma = 0.4*pmb.units.nm,
                    epsilon = 1*pmb.units('reduced_energy'))

pmb.define_particle(name = PDha_carboxyl_bead, 
                    z = 0, 
                    sigma = 0.5*pmb.units.nm, 
                    epsilon = 1*pmb.units('reduced_energy'))

pmb.define_particle(name = PDha_amine_bead, 
                    z = 0, 
                    sigma = 0.3*pmb.units.nm, 
                    epsilon = 1*pmb.units('reduced_energy'))

Then, one defines templates for the polymer residues. A residue is composed by a `central_bead` where one or various `side_chains` are attached. Each side chain can contain one particle or other residues.

In [14]:
PDha_residue = 'PDha_mon'

pmb.define_residue(name = PDha_residue, 
                   central_bead = PDha_backbone_bead,
                   side_chains = [PDha_carboxyl_bead, PDha_amine_bead])

We can check the residue templates we defined in the pyMBE database:

In [15]:
pmb.get_templates_df(pmb_type = 'residue')

  pmb_type      name central_bead            side_chains
0  residue  PDha_mon      BB-PDha  [COOH-PDha, NH3-PDha]

Once done, one has to define templates for bonds between each pair of different particle templates in the polymer. For simplicity, in this tutorial we assume that all bonds are equal and we set-up all bonds using a harmonic potential with the following arbitrary parameters.

In [16]:
bond_type = 'harmonic'
generic_bond_lenght=0.4 * pmb.units.nm
generic_harmonic_constant = 400 * pmb.units('reduced_energy / reduced_length**2')

harmonic_bond = {'r_0'    : generic_bond_lenght,
                 'k'      : generic_harmonic_constant}

pmb.define_bond(bond_type = bond_type,
                bond_parameters = harmonic_bond,
                particle_pairs = [[PDha_backbone_bead, PDha_backbone_bead],
                                  [PDha_backbone_bead, PDha_carboxyl_bead],
                                  [PDha_backbone_bead, PDha_amine_bead]])

All bond templates we defined are stored in the pyMBE database:

In [17]:
pmb.get_templates_df(pmb_type = 'bond')

/usr/bin/eog: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE

,pmb_type,name,bond_type,particle_name1,particle_name2,parameters
0,bond,BB-PDha-BB-PDha,harmonic,BB-PDha,BB-PDha,"{'r_0': 0.4 nanometer, 'k': 41108.12659373736 ..."
1,bond,BB-PDha-COOH-PDha,harmonic,BB-PDha,COOH-PDha,"{'r_0': 0.4 nanometer, 'k': 41108.12659373736 ..."
2,bond,BB-PDha-NH3-PDha,harmonic,BB-PDha,NH3-PDha,"{'r_0': 0.4 nanometer, 'k': 41108.12659373736 ..."

NOTE: Currently, only harmonic and FENE bonds are supported.

Finally, one defines a molecule template. A molecule template is defined by a linear sequence of residues, `residue_list`. For instance a decamer should be created as follows:

In [18]:
PDha_polymer = 'PDha'
N_monomers = 10

pmb.define_molecule(name = PDha_polymer,
                    residue_list = [PDha_residue]*N_monomers)

All defined molecule templates can be consulted in the pyMBE database

In [19]:
pmb.get_templates_df(pmb_type = 'molecule')

   pmb_type  name                                       residue_list
0  molecule  PDha  [PDha_mon, PDha_mon, PDha_mon, PDha_mon, PDha_...

After defining a template for the polymer, we are ready to create one PdHa polymer in the center of the simulation box.

In [20]:
N_polymers = 1

molecule_ids = pmb.create_molecule(name = PDha_polymer, 
                                    number_of_molecules = N_polymers,
                                    espresso_system = espresso_system, 
                                    list_of_first_residue_positions = [[Box_L.to('reduced_length').magnitude/2]*3])

All instances of particles, residues, bonds and molecules created into ESPResSo are bookkept in the pyMBE database:

In [21]:
# Check particle instances
pmb.get_instances_df(pmb_type = 'particle')

,pmb_type,name,particle_id,initial_state,residue_id,molecule_id,assembly_id
0,particle,BB-PDha,0,BB-PDha,0,0,<NA>
1,particle,COOH-PDha,1,COOH-PDha,0,0,<NA>
2,particle,NH3-PDha,2,NH3-PDha,0,0,<NA>
3,particle,BB-PDha,3,BB-PDha,1,0,<NA>
4,particle,COOH-PDha,4,COOH-PDha,1,0,<NA>
5,particle,NH3-PDha,5,NH3-PDha,1,0,<NA>
6,particle,BB-PDha,6,BB-PDha,2,0,<NA>
7,particle,COOH-PDha,7,COOH-PDha,2,0,<NA>
8,particle,NH3-PDha,8,NH3-PDha,2,0,<NA>
9,particle,BB-PDha,9,BB-PDha,3,0,<NA>
10,particle,COOH-PDha,10,COOH-PDha,3,0,<NA>
11,particle,NH3-PDha,11,NH3-PDha,3,0,<NA>
12,particle,BB-PDha,12,BB-PDha,4,0,<NA>
13,particle,COOH-PDha,13,COOH-PDha,4,0,<NA>
14,particle,NH3-PDha,14,NH3-PDha,4,0,<NA>
15,particle,BB-PDha,15,BB-PDha,5,0,<NA>
16,particle,COOH-PDha,16,COOH-PDha,5,0,<NA>
17,particle,NH3-PDha,17,NH3-PDha,5,0,<NA>
18,particle,BB-PDha,18,BB-PDha,6,0,<NA>
19,particle,COOH-PDha,19,COOH-PDha,6,0,<NA>
20,particle,NH3-PDha,20,NH3-PDha,6,0,<NA>
21,particle,BB-PDha,21,BB-PDha,7,0,<NA>
22,particle,COOH-PDha,22,COOH-PDha,7,0,<NA>
23,particle,NH3-PDha,23,NH3-PDha,7,0,<NA>
24,particle,BB-PDha,24,BB-PDha,8,0,<NA>
25,particle,COOH-PDha,25,COOH-PDha,8,0,<NA>
26,particle,NH3-PDha,26,NH3-PDha,8,0,<NA>
27,particle,BB-PDha,27,BB-PDha,9,0,<NA>
28,particle,COOH-PDha,28,COOH-PDha,9,0,<NA>
29,particle,NH3-PDha,29,NH3-PDha,9,0,<NA>

In [22]:
# Check residue instances
pmb.get_instances_df(pmb_type = 'residue')

  pmb_type      name  residue_id  molecule_id assembly_id
0  residue  PDha_mon           0            0        <NA>
1  residue  PDha_mon           1            0        <NA>
2  residue  PDha_mon           2            0        <NA>
3  residue  PDha_mon           3            0        <NA>
4  residue  PDha_mon           4            0        <NA>
5  residue  PDha_mon           5            0        <NA>
6  residue  PDha_mon           6            0        <NA>
7  residue  PDha_mon           7            0        <NA>
8  residue  PDha_mon           8            0        <NA>
9  residue  PDha_mon           9            0        <NA>

In [23]:
# Check bond instances
pmb.get_instances_df(pmb_type = 'bond')

   pmb_type               name  bond_id  particle_id1  particle_id2
0      bond  BB-PDha-COOH-PDha        0             0             1
1      bond   BB-PDha-NH3-PDha        1             0             2
2      bond  BB-PDha-COOH-PDha        2             3             4
3      bond   BB-PDha-NH3-PDha        3             3             5
4      bond    BB-PDha-BB-PDha        4             0             3
5      bond  BB-PDha-COOH-PDha        5             6             7
6      bond   BB-PDha-NH3-PDha        6             6             8
7      bond    BB-PDha-BB-PDha        7             3             6
8      bond  BB-PDha-COOH-PDha        8             9            10
9      bond   BB-PDha-NH3-PDha        9             9            11
10     bond    BB-PDha-BB-PDha       10             6             9
11     bond  BB-PDha-COOH-PDha       11            12            13
12     bond   BB-PDha-NH3-PDha       12            12            14
13     bond    BB-PDha-BB-PDha       13             9            12
14     bond  BB-PDha-COOH-PDha       14            15            16
15     bond   BB-PDha-NH3-PDha       15            15            17
16     bond    BB-PDha-BB-PDha       16            12            15
17     bond  BB-PDha-COOH-PDha       17            18            19
18     bond   BB-PDha-NH3-PDha       18            18            20
19     bond    BB-PDha-BB-PDha       19            15            18
20     bond  BB-PDha-COOH-PDha       20            21            22
21     bond   BB-PDha-NH3-PDha       21            21            23
22     bond    BB-PDha-BB-PDha       22            18            21
23     bond  BB-PDha-COOH-PDha       23            24            25
24     bond   BB-PDha-NH3-PDha       24            24            26
25     bond    BB-PDha-BB-PDha       25            21            24
26     bond  BB-PDha-COOH-PDha       26            27            28
27     bond   BB-PDha-NH3-PDha       27            27            29
28     bond    BB-PDha-BB-PDha       28            24            27

In [24]:
# Check molecule instances
pmb.get_instances_df(pmb_type = 'molecule')

   pmb_type  name  molecule_id assembly_id
0  molecule  PDha            0        <NA>

Now, let us see what we have created...

In [25]:
picture_name = 'PDha_system.png'
create_snapshot_of_espresso_system(espresso_system = espresso_system, 
                              filename = picture_name)
img = Image.open(picture_name)
img.show()

Delete the particles and check that there are no particle instances in the pyMBE database

In [26]:
pmb.delete_instances_in_system(instance_id=molecule_ids[0],
                               pmb_type="molecule", 
                              espresso_system = espresso_system)
# Check particle instances
pmb.get_instances_df(pmb_type = 'particle')

Empty DataFrame
Columns: []
Index: []

## How to create complex polymers <a class="anchor" id="complex_polymers"></a>

pyMBE can also be used to setup models that requiere more complex side chains, i.e. with more than one bead per side chain. One example of these complex molecules is the poly(N,N-diallylglutamate) (PDAGA), whose structure is depicted in the figure below. Following the logic of the previous example, one would construct PDAGA with pyMBE by defining a `residue` with a `central_bead` for the polymer backbone (grey) and a `side_chain` attached to it. In this case, the group in the side chain of the PDAGA monomer has a complex structure. This group can be coarse-grained by defining another `residue`  composed by a new `central_bead` which represents the cyclic amine group (blue) and two `side_chains` ($\alpha$ and $\beta$ carboxyl) attached to it (red and orange).

<img src="../figs/PDAGA.png" width=150 height=150 />

One can start by defining templates for each different bead of the PDAGA.

In [27]:
PDAGA_backbone_bead = 'BB-PDAGA'
PDAGA_cyclic_amine_bead = 'NH3-PDAGA'
PDAGA_alpha_carboxyl_bead = 'aCOOH-PDAGA'
PDAGA_beta_carboxyl_bead = 'bCOOH-PDAGA'

pmb.define_particle(name = PDAGA_backbone_bead, 
                    z = 0,
                    sigma = 0.4*pmb.units.nm, 
                    epsilon = 1*pmb.units('reduced_energy'))

pmb.define_particle(name = PDAGA_cyclic_amine_bead, 
                    z = 0, 
                    sigma = 0.3*pmb.units.nm, 
                    epsilon = 1*pmb.units('reduced_energy'))

pmb.define_particle(name = PDAGA_alpha_carboxyl_bead, 
                    z = 0, 
                    sigma = 0.2*pmb.units.nm, 
                    epsilon = 1*pmb.units('reduced_energy'))

pmb.define_particle(name = PDAGA_beta_carboxyl_bead, 
                    z = 0, 
                    sigma = 0.4*pmb.units.nm, 
                    epsilon = 1*pmb.units('reduced_energy'))

The next step is to define the two different residue templates: 
1. The side chain: two carboxyl beads attached to the cyclic amine bead.

In [28]:
PDAGA_side_chain_residue = 'PDAGA_side_chain_residue'

pmb.define_residue (name = PDAGA_side_chain_residue,
                    central_bead = PDAGA_cyclic_amine_bead,
                    side_chains = [PDAGA_alpha_carboxyl_bead, PDAGA_beta_carboxyl_bead])

2. Each monomeric unit of the PDAGA: the side chain defined above attached to the backbone.

In [29]:
PDAGA_monomer_residue = 'PDAGA_monomer_residue'
pmb.define_residue( name = PDAGA_monomer_residue,
                    central_bead = PDAGA_backbone_bead,
                    side_chains = [PDAGA_side_chain_residue])

Then, we need to define bond templates in a similar way as for the case of the simple polymer.

In [30]:
bond_type = 'harmonic'
generic_bond_lenght=0.4 * pmb.units.nm
generic_harmonic_constant = 400 * pmb.units('reduced_energy / reduced_length**2')

harmonic_bond = {'r_0'    : generic_bond_lenght,
                 'k'      : generic_harmonic_constant,
                 }

pmb.define_bond(bond_type = bond_type,
                bond_parameters = harmonic_bond,
                particle_pairs = [[PDAGA_backbone_bead, PDAGA_backbone_bead],
                                  [PDAGA_backbone_bead, PDAGA_cyclic_amine_bead],
                                  [PDAGA_alpha_carboxyl_bead, PDAGA_cyclic_amine_bead],
                                  [PDAGA_beta_carboxyl_bead, PDAGA_cyclic_amine_bead]])

Now, let us define an octamer of PDAGA.

In [ ]:
PDAGA_polymer = 'PDAGA'
N_monomers = 8

pmb.define_molecule(name = PDAGA_polymer,
                    residue_list = [PDAGA_monomer_residue]*N_monomers)

/usr/bin/eog: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE

Finally, we are able to create a PDAGA polymer into the ESPResSo system.

In [32]:
N_polymers = 1

mol_ids = pmb.create_molecule(name = PDAGA_polymer,
                            number_of_molecules= N_polymers,
                            espresso_system = espresso_system,
                            list_of_first_residue_positions = [[Box_L.to('reduced_length').magnitude/2]*3])

Now, let us see our PDAGA molecule.

In [33]:
picture_name = 'PDAGA_system.png'
create_snapshot_of_espresso_system(espresso_system = espresso_system, 
                               filename = picture_name)
img = Image.open(picture_name)
img.show()

Delete the particles and check that the pyMBE database is empty.

In [34]:

for mol_id in mol_ids:
    pmb.delete_instances_in_system(instance_id=mol_id,
                                   pmb_type="molecule",
                                   espresso_system=espresso_system)
pmb.get_instances_df(pmb_type = 'particle')

Empty DataFrame
Columns: []
Index: []

## How to create di-block copolymers <a class="anchor" id="diblock_copolymers"></a>

In turn, the residues previously defined to build the PDAGA and PDha molecules can be used to build more complex polymers such as a di-block PDha-PDAGA copolymer, as shown in the picture below

<img src="../figs/PDAGA_PDha_diblock_copolymer.png" width=250 height=250 />

Define the bond template between the backbone particle of PDha and the backbone particle of PDAGA

In [35]:

pmb.define_bond(bond_type = bond_type,
                bond_parameters = harmonic_bond,
                particle_pairs = [[PDha_backbone_bead, PDAGA_backbone_bead]])

Define a molecule template for the di-block polymer molecule using Python list comprehension methods

In [36]:
N_monomers_PDha = 4
N_monomers_PDAGA = 4
diblock_polymer = 'diblock'

pmb.define_molecule(name = diblock_polymer,
                    residue_list = [PDha_residue]*N_monomers_PDha+[PDAGA_monomer_residue]*N_monomers_PDAGA)

Creating the di-block polymer into the ESPResSo system

In [37]:
N_polymers = 1

mol_ids = pmb.create_molecule(name = diblock_polymer,
                              number_of_molecules= N_polymers,
                              espresso_system = espresso_system,
                              list_of_first_residue_positions = [[Box_L.to('reduced_length').magnitude/2]*3]) 
# See the particle instances you have created
pmb.get_instances_df(pmb_type="particle")

/usr/bin/eog: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE

,pmb_type,name,particle_id,initial_state,residue_id,molecule_id,assembly_id
0,particle,BB-PDha,0,BB-PDha,0,0,<NA>
1,particle,COOH-PDha,1,COOH-PDha,0,0,<NA>
2,particle,NH3-PDha,2,NH3-PDha,0,0,<NA>
3,particle,BB-PDha,3,BB-PDha,1,0,<NA>
4,particle,COOH-PDha,4,COOH-PDha,1,0,<NA>
5,particle,NH3-PDha,5,NH3-PDha,1,0,<NA>
6,particle,BB-PDha,6,BB-PDha,2,0,<NA>
7,particle,COOH-PDha,7,COOH-PDha,2,0,<NA>
8,particle,NH3-PDha,8,NH3-PDha,2,0,<NA>
9,particle,BB-PDha,9,BB-PDha,3,0,<NA>
10,particle,COOH-PDha,10,COOH-PDha,3,0,<NA>
11,particle,NH3-PDha,11,NH3-PDha,3,0,<NA>
12,particle,BB-PDAGA,12,BB-PDAGA,4,0,<NA>
13,particle,NH3-PDAGA,13,NH3-PDAGA,4,0,<NA>
14,particle,aCOOH-PDAGA,14,aCOOH-PDAGA,4,0,<NA>
15,particle,bCOOH-PDAGA,15,bCOOH-PDAGA,4,0,<NA>
16,particle,BB-PDAGA,16,BB-PDAGA,5,0,<NA>
17,particle,NH3-PDAGA,17,NH3-PDAGA,5,0,<NA>
18,particle,aCOOH-PDAGA,18,aCOOH-PDAGA,5,0,<NA>
19,particle,bCOOH-PDAGA,19,bCOOH-PDAGA,5,0,<NA>
20,particle,BB-PDAGA,20,BB-PDAGA,6,0,<NA>
21,particle,NH3-PDAGA,21,NH3-PDAGA,6,0,<NA>
22,particle,aCOOH-PDAGA,22,aCOOH-PDAGA,6,0,<NA>
23,particle,bCOOH-PDAGA,23,bCOOH-PDAGA,6,0,<NA>
24,particle,BB-PDAGA,24,BB-PDAGA,7,0,<NA>
25,particle,NH3-PDAGA,25,NH3-PDAGA,7,0,<NA>
26,particle,aCOOH-PDAGA,26,aCOOH-PDAGA,7,0,<NA>
27,particle,bCOOH-PDAGA,27,bCOOH-PDAGA,7,0,<NA>

Now, let us see our di-block PDha-PDAGA molecule.

In [38]:
picture_name = 'diblock_system.png'
create_snapshot_of_espresso_system(espresso_system = espresso_system, 
                               filename = picture_name)
img = Image.open(picture_name)
img.show()

Delete the particles and check that our df is empty.

In [39]:
for mol_id in mol_ids:
    pmb.delete_instances_in_system(instance_id=0, 
                                   pmb_type="molecule",
                                   espresso_system = espresso_system)
pmb.get_instances_df(pmb_type="particle")

Empty DataFrame
Columns: []
Index: []

## Practice by creating a custom polyampholyte chain <a class="anchor" id="branched_polyampholytes"></a>

Polyampholytes are polymers containing both acidic and basic groups on the same molecule, one example of a branched polyampholyte is depicted in the figure below.

<img src="../figs/branched_polyampholyte.png" width=350 height=350 />

We will create the polyampholyte chain in the figure, starting by defining two different residues, 'Res_1' and 'Res_2'. The polyampholyte chain is then defined by following residue_list:

residue_list = 2*["Res_1"] + ["Res_2"] + 2*["Res_1"] + 2*["Res_2"]

### Tasks to do:

1. Define particle templates for each different bead in the residues using "pmb.define_particle". There are 3 different particles, an inert particle, an acidic particle with pKa = 4, and a basic particle with pKa = 9.
2. Define residue templates using "pmb.define_residue". "Res_1" consists of an inert particle as central bead and acidic and basic particles as side chain. "Res_2" consists of an inert particle as central bead and "Res_1" as side chain.
3. Define bond templates for each pair of particle templates.  
4. Define a molecule template for the branched polyampholyte chain using "pmb.define_molecule" with the above "residue_list." 
5. Create the branched polyampholyte into the ESPResSo system.
6. Visualize your creation.
7. Delete the molecule and check that the pyMBE database is empty.

#### 1. Define particle templates for each different bead of Res_1 and Res_2.

#### 2. Define the residue templates for Res_1 and Res_2.

3. Define bond templates for each pair of particle templates.

#### 3. Define a molecule template for the diblock polyampholyte.

#### 4. Create the diblock polyampholyte chain into the ESPResSo system.

#### 5. Visualize your creation.

#### 6. Delete the molecule and check that the pyMBE database is empty.

Refer to the sample script "branched_polyampholyte.py" in the samples folder for a complete solution of this exercise.

## How to create peptides <a class="anchor" id="peptides"></a>

pyMBE includes built-on functions to facilitate the setting up of coarse-grained models for peptides from their aminoacid sequence. Currently, there are two different coarse-grained models implemented: 

* `1beadAA`, where the aminoacid is represented by one single bead.
* `2beadAA`, where the aminoacid is represented by two beads (backbone and side-chain). 

We provide reference parameters in the folder (`pyMBE/parameters`) which can be loaded into pyMBE. The peptide sequence should be provided as a `str` composed either by the list of the one letter code or the list of the three letter code of the corresponding aminoacids. For example, the two possible ways to provide the peptide Cysteine$_3$ - Glutamic acid$_2$ - Histidine$_4$ - Valine are:

* one letter code: 'CCCEEHHHHV'
* three letter code: 'CYS-CYS-CYS-GLU-GLU-HIS-HIS-HIS-HIS-VAL'

Let's set up the peptide Lysine$_5$ - Glutamic acid$_5$ using a two beads coarse-grained model.

In [40]:
N_peptide = 1
sequence = "KKKKKEEEEE"
model = '2beadAA'

We can use the peptide parametrization reported by Lunkad et al. [2], which is provided in the reference folder. This parametrization includes information about the particles (i.e. their Lennard-Jones parameters) and their bonding potentials (harmonic bonds).

In [ ]:
path_to_interactions=pmb.root / "parameters" / "peptides" / "Lunkad2021"
path_to_pka=pmb.root / "parameters" / "pka_sets" / "Hass2015.json"
pmb.load_database(folder=path_to_interactions) 
pmb.get_templates_df(pmb_type="particle")
pmb.get_templates_df(pmb_type="bond")

,pmb_type,name,sigma,epsilon,cutoff,offset,initial_state
0,particle,CA,0.35 nanometer,25.69257912108585 millielectron_volt,0.3984740271498274 nanometer,0.0 nanometer,CA
1,particle,D,0.35 nanometer,25.69257912108585 millielectron_volt,0.3984740271498274 nanometer,0.0 nanometer,DH
2,particle,E,0.35 nanometer,25.69257912108585 millielectron_volt,0.3984740271498274 nanometer,0.0 nanometer,EH
3,particle,H,0.35 nanometer,25.69257912108585 millielectron_volt,0.3984740271498274 nanometer,0.0 nanometer,HH
4,particle,Y,0.35 nanometer,25.69257912108585 millielectron_volt,0.3984740271498274 nanometer,0.0 nanometer,YH
5,particle,K,0.35 nanometer,25.69257912108585 millielectron_volt,0.3984740271498274 nanometer,0.0 nanometer,KH

/usr/bin/eog: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE

Additionally, we can load one of the reference sets of pKa values for amino acids that we provide in pyMBE

In [42]:
pmb.load_pka_set(path_to_pka)
# Check the loaded pKa set
pmb.get_reactions_df()

,reaction,stoichiometry,pK,reaction_type,metadata,simulation_method
0,DH <-> D,"{'DH': -1, 'D': 1}",4.0,monoprotic_acid,"{'summary': 'pKa-values of Hass et al.', 'sour...",None
1,EH <-> E,"{'EH': -1, 'E': 1}",4.4,monoprotic_acid,"{'summary': 'pKa-values of Hass et al.', 'sour...",None
2,YH <-> Y,"{'YH': -1, 'Y': 1}",9.6,monoprotic_acid,"{'summary': 'pKa-values of Hass et al.', 'sour...",None
3,CH <-> C,"{'CH': -1, 'C': 1}",8.3,monoprotic_acid,"{'summary': 'pKa-values of Hass et al.', 'sour...",None
4,HH <-> H,"{'HH': -1, 'H': 1}",6.8,monoprotic_base,"{'summary': 'pKa-values of Hass et al.', 'sour...",None
5,KH <-> K,"{'KH': -1, 'K': 1}",10.4,monoprotic_base,"{'summary': 'pKa-values of Hass et al.', 'sour...",None
6,RH <-> R,"{'RH': -1, 'R': 1}",13.5,monoprotic_base,"{'summary': 'pKa-values of Hass et al.', 'sour...",None
7,nH <-> n,"{'nH': -1, 'n': 1}",8.0,monoprotic_base,"{'summary': 'pKa-values of Hass et al.', 'sour...",None
8,cH <-> c,"{'cH': -1, 'c': 1}",3.6,monoprotic_acid,"{'summary': 'pKa-values of Hass et al.', 'sour...",None

Since monoprotic acid/base particles can be in two possible states, protonated and deprotonated, we need to define templates for those particle states

In [ ]:
# Get the pKa set stored in pyMBE
pka_set = pmb.get_pka_set()
# Check the pka_set
print(pka_set)
# define templates for the different particle states of monoprotic acid an basic groups:
for acidbase_particle in pka_set.keys():
    pmb.define_monoprototic_particle_states(particle_name=acidbase_particle,
                                            acidity=pka_set[acidbase_particle]["acidity"])
pmb.get_templates_df(pmb_type="particle_state")

{'D': {'pka_value': 4.0, 'acidity': 'acidic'}, 'E': {'pka_value': 4.4, 'acidity': 'acidic'}, 'Y': {'pka_value': 9.6, 'acidity': 'acidic'}, 'C': {'pka_value': 8.3, 'acidity': 'acidic'}, 'H': {'pka_value': 6.8, 'acidity': 'basic'}, 'K': {'pka_value': 10.4, 'acidity': 'basic'}, 'R': {'pka_value': 13.5, 'acidity': 'basic'}, 'n': {'pka_value': 8.0, 'acidity': 'basic'}, 'c': {'pka_value': 3.6, 'acidity': 'acidic'}}

ValueError: Acidity {'pka_value': 4.0, 'acidity': 'acidic'} provided for particle name  D is not supported. Valid keys are: ['acidic', 'basic']

The above functions define templates for particles and particle states Before creating a peptide molecule, we also need to define templates for the aminoacid residues and the peptide molecule

In [43]:
from pyMBE.lib.handy_functions import define_peptide_AA_residues

# This is a convinience function that defines residue templates
# for aminoacids based on some pre-defined models
define_peptide_AA_residues(sequence=sequence,
                           model=model,
                           pmb=pmb)
pmb.define_peptide(name = sequence, 
                   sequence = sequence, 
                   model = model)
pmb.get_templates_df(pmb_type="residue")
pmb.get_templates_df(pmb_type="peptide")

,pmb_type,name,model,residue_list,sequence
0,peptide,KKKKKEEEEE,2beadAA,"[AA-K, AA-K, AA-K, AA-K, AA-K, AA-E, AA-E, AA-...",KKKKKEEEEE

Now, we can create instances of our peptide template into the ESPResSo system.

In [44]:

mol_ids = pmb.create_molecule(name = sequence,
                            number_of_molecules=  N_peptide,
                            espresso_system = espresso_system,
                            list_of_first_residue_positions = [[Box_L.to('reduced_length').magnitude/2]*3])
pmb.get_instances_df(pmb_type="peptide")

ValueError: Template 'KH' not found in type 'particle_state'.

Let us visualize our peptide.

In [ ]:
picture_name = 'peptide.png'
create_snapshot_of_espresso_system(espresso_system = espresso_system, 
                               filename = picture_name)
img = Image.open(picture_name)
img.show()

Delete the particles and check that the pyMBE database is empty

In [ ]:
for mol_id in mol_ids:
    pmb.delete_instances_in_system(instance_id=0,
                                   pmb_type="peptide", 
                                   espresso_system = espresso_system)

### References

[1] Beyer, D., Torres, P. B., Pineda, S. P., Narambuena, C. F., Grad, J. N., Košovan, P., & Blanco, P. M. (2024). pyMBE: The Python-based molecule builder for ESPResSo. The Journal of Chemical Physics, 161(2).
[2] Lunkad, R., Murmiliuk, A., Hebbeker, P., Boublík, M., Tošner, Z., Štěpánek, M., & Košovan, P. (2021). Quantitative prediction of charge regulation in oligopeptides. Molecular Systems Design & Engineering, 6(2), 122-131.